name: SafeZone
main: me.james.safezone.SafeZone
version: 1.0
api-version: 1.13
commands:
  safezone:
    description: Manage safe zones
    usage: /safezone <set|remove> <name> [width] [length]